# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

# Use cargo to test the project
test:cargo:
  before_script:
    - apt-get update -qq && apt-get install -y -qq libsamplerate0-dev libsndfile1-dev
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose
  cache:
    paths:
      - target/
      - cargo/
  tags:
    - linux
    - docker
