#!/usr/bin/python3

"""
This script formats the analyzes generated by analyze.py
It creates a tsv file ready to be consumed for a latex table.
"""

import sys
import os
import glob
import subprocess
from tqdm import tqdm, trange
import numpy as np
from datetime import timedelta
import csv
from collections import defaultdict
from operator import itemgetter, attrgetter

# "ExpectRemainingTime"
columnNames = ["NbCycles", "NbEdges", "Budget",  "ExpectRemainingTime", "Deadline", "NbResamplers", "NbDegradedNodes", "ExecutionTime", "ChoosingDuration"]
#meanNames = ["mean"+s for s in columnNames]
#stdNames = ["std"+s for s in columnNames]
fieldnames = ["nbNodes", "Mode", "Degraded"] + columnNames


folderName = sys.argv[1]
os.chdir(folderName)
folderName = folderName.rstrip("/")
#the file name must be foldername.tsv
filename = folderName + ".tsv"
data = np.genfromtxt(filename, delimiter="\t", encoding=None, dtype=None, names=True)
dtyp = data.dtype


results=[]
for line in data:
    result={}
    nbCycles = line["meanNbCycles"]
    result["nbNodes"] = line["nbNodes"]
    for columnName in columnNames:
        result[columnName] = line["mean" + columnName]
    if line["Mode"] == "EX":
        result["Mode"] = "TOT"
    else:
        result["Mode"] = "PROG"
    result["Degraded"] = 100. * line["meanNbDegradedCycles"] / float(nbCycles)
    results.append(result)

results.sort(key=lambda res : res["nbNodes"])
#results.sort(key=attrgetter("nbNodes"))

print("Writing final result file")
with open(folderName+"-summary.tsv", 'w') as tsvfile:
    writer = csv.DictWriter(tsvfile, fieldnames,dialect="excel-tab")
    writer.writeheader()
    for result in tqdm(results):
        writer.writerow(result)
